import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guidesSidebar: [{type: 'autogenerated', dirName: 'guides'}],
  promptsSidebar: [{type: 'autogenerated', dirName: 'prompts'}],
  appsSidebar: [{type: 'autogenerated', dirName: 'apps'}],
  advancedSidebar: [{type: 'autogenerated', dirName: 'advanced'}],
  bizSidebar: [{type: 'autogenerated', dirName: 'biz'}],
  adapterSidebar: [
    {
      type: 'doc',
      id: 'adapter/index',
      label: 'Зачем нужен адаптер?',
    },
    {
      type: 'doc',
      id: 'adapter/quickstart',
      label: 'Начало работы',
    },
    {
      type: 'category',
      label: 'Функционал',
      items: [
        'adapter/functionality/basics',
        'adapter/functionality/autoauth',
        'adapter/functionality/clf',
        'adapter/functionality/using-tools'
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Примеры',
      link: {
        type: 'generated-index',
        title: 'Примеры',
        description: 'Примеры использования адаптера',
        slug: '/adapter/examples',
      },
      items: [
        'adapter/examples/langchain',
        'adapter/examples/sdk-py',
        'adapter/examples/sdk-js',
      ],
    },
    {
      type: 'doc',
      id: 'adapter/stability-safety',
      label: 'Стабильность и безопасность',
    },
    {
      type: 'link',
      label: 'Source code',
      href: 'https://github.com/all-mute/openai2yandex_api_adapter',
    },
    {
      type: 'doc',
      id: 'adapter/deploy',
      label: 'Self-hosting',
    },
    {
      type: 'doc',
      id: 'adapter/help',
      label: 'Помощь',
    },

  ],
};

export default sidebars;
