import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guidesSidebar: [{type: 'autogenerated', dirName: 'guides'}],
  promptsSidebar: [{type: 'autogenerated', dirName: 'prompts'}],
  appsSidebar: [{type: 'autogenerated', dirName: 'apps'}],
  advancedSidebar: [{type: 'autogenerated', dirName: 'advanced'}],
  bizSidebar: [
    {
      type: 'category',
      label: 'Популярные сценарии',
      items: [
        'biz/main/coding'
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Прочее',
      items: [
        'biz/secondary/FC_why',
        'biz/secondary/searc-suggestions-w-gpt',
      ],
    },
  ],
  adapterSidebar: [
    {
      type: 'doc',
      id: 'adapter/index',
      label: 'Зачем нужен адаптер?',
    },
    {
      type: 'doc',
      id: 'adapter/quickstart',
      label: 'Начало работы',
    },
    {
      type: 'doc',
      id: 'adapter/public-endpoints',
      label: 'Публичные эндпоинты',
    },
    {
      type: 'category',
      label: 'Функционал',
      items: [
        'adapter/functionality/basics',
        'adapter/functionality/clf',
        'adapter/functionality/using-tools',
        'adapter/functionality/mapping',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Примеры',
      items: [
        'adapter/examples/langchain',
        'adapter/examples/sdk-py',
        'adapter/examples/sdk-js',
      ],
    },
    {
      type: 'link',
      label: 'Source code',
      href: 'https://github.com/ai-cookbook/openai-yandexgpt-adapter',
    },
    {
      type: 'doc',
      id: 'adapter/deploy',
      label: 'Self-hosting',
    },
    {
      type: 'doc',
      id: 'adapter/help',
      label: 'Помощь',
    },

  ],
  etcSidebar: [
    {
      type: 'autogenerated',
      dirName: 'etc',
    },
  ],
};

export default sidebars;
